name: Tests

on: [push]

env:
  PYTHON_VERSION: '3.12'
  AWS_REGION: 'us-west-1'
jobs:
    run-tests:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v4
            with:
              fetch-depth: 1
              fetch-tags: true

# Necessary action when needing to use AWS credentials.
          - name: Configure AWS Credentials
            uses: aws-actions/configure-aws-credentials@v4
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: ${{ env.AWS_REGION }}

          - name: Install Python
            uses: actions/setup-python@v5
            with:
              python-version: ${{ env.PYTHON_VERSION }}

          - name: Install Dependencies
            run: |
              sudo pip install uv
              uv pip install --system --break-system-packages awscli coverage setuptools
              uv pip install --system --break-system-packages -r requirements.txt

          - name: Setup Mosek License File
            run: |
              sudo mkdir /root/mosek
              mkdir $HOME/mosek
              aws s3 cp s3://slac.gismo.ci.artifacts/mosek.license/mosek.lic $HOME/mosek/mosek.lic
              sudo cp $HOME/mosek/mosek.lic /root/mosek/mosek.lic

# Current unit test is not consistent. Occasionally fails despite usually passing. Needs to be fixed.
          - name: Run Unit Tests
            run: python3 -m coverage run -m unittest
